### ISSUE TITLE
Deprecate the unused npm package

### ISSUE THREAD

**Issue by ChihChengLiang** [thehubbleproject/hubble-bls#18]
### What's wrong

- We've been releasing in https://www.npmjs.com/package/@thehubbleproject/bls
- We've released once in https://www.npmjs.com/package/hubble-bls, but no longer maintained

The two packages confuse the developers. We should deprecate the unmaintained one somehow.

### How can we fix it

Not sure yet

**Comment by jacque006** [comment]
@ChihChengLiang We can do this via https://docs.npmjs.com/cli/v8/commands/npm-deprecate for all published versions of `hubble-bls` and have the message point to the new package. If you want to add me as an owner to `hubble-bls` on npmjs.com I'd be more than happy to take care of this.

**Comment by ChihChengLiang** [comment]
Thank you @jacque006 so much for taking initiative on this. I've added you as the package maintainer on npmjs.com.

**Comment by jacque006** [comment]
https://www.npmjs.com/package/hubble-bls

![Screenshot from 2022-03-11 18-01-56](https://user-images.githubusercontent.com/10394161/157986040-ce4a5b1b-071a-417d-b86c-cfc41b4839c6.png)

`npm install hubble-bls`:
```
npm WARN deprecated hubble-bls@0.0.1: hubble-bls is no longer maintained, use @thehubbleproject/bls instead
```
