### ISSUE TITLE
bump mcl-wasm package version to 1.0.0

### ISSUE THREAD

**Issue by jacque006** [thehubbleproject/hubble-bls#24]
`mcl-wasm` now has a stable major version [v1.0.0](https://www.npmjs.com/package/mcl-wasm/v/1.0.0). A brief parse of the [chnagelog](https://github.com/herumi/mcl-wasm/blob/master/readme.md#news) does not seem to show any major changes.

**Comment by jacque006** [comment]
@ChihChengLiang If this update looks good to you and you don't see any compatibility issues with the new `mcl-wasm`, I can take on this issue.

**Comment by jacque006** [comment]
Might also be worth bumping the `ethers` version as well.

**Comment by ChihChengLiang** [comment]
Yeah, that mcl-wasm upgrade looks good to me. And the typescript feature looks pretty cool!
Bumping the ethers version sounds good too.
Thank you @jacque006 for taking on this issue.
